# Generated by Django 4.1.2 on 2022-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar',
            field=models.IntegerField(null=True, unique=True, verbose_name='Aadhar'),
        ),
    ]
