# Generated by Django 4.1.2 on 2022-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kalinga_id',
            field=models.CharField(max_length=40, null=True, verbose_name='Kalinga ID'),
        ),
    ]
